### ISSUE TITLE
Invalid Syntax Error on import statement

### ISSUE THREAD

**Issue by sagarb311** [divinorum-webb/tableau-api-lib#9]
Hello, 

I installed this library using pip on a virtual environment using Python 3.5.1 
When I run the import statement, it throws an error. 

## Installation Steps 
`pip install tableau-api-lib`

## To Reproduce Error
`import tableau_api_lib`

**Error:**
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/<sdgfdhs>/.pyenv/versions/<fdsfdsfdgg>/lib/python3.5/site-packages/tableau_api_lib/__init__.py", line 1, in <module>
    from tableau_api_lib.tableau_server_connection import TableauServerConnection
  File "/Users/<sfsfsgsg>/.pyenv/versions/<fsdfdsgfsg>/lib/python3.5/site-packages/tableau_api_lib/tableau_server_connection.py", line 926
    'filter': f'filter=viewUrlName:eq:{view_name.replace(" ", "")}'
                                                                  ^
SyntaxError: invalid syntax
`

**Comment by divinorum-webb** [comment]
Hi, that error is being thrown because Python 3.5 does not support [f-strings](https://realpython.com/python-f-strings/).
If using Python 3.6 or higher, this will not be an issue.
